### ISSUE TITLE
命名規則について

### ISSUE THREAD

**Issue by tecsoc** [tks3210/autoJudge#2]
変数は全て小文字というような命名規則になっているような気がしたのでこちらもそれに準拠して作ったのですが、大文字やアンダーバーがないと単語の区切りが分かりにくいので違う方がいいかもしれません。どうせなら関数名など全てPEP8に準拠したい気がします。
[参考リンク](https://qiita.com/shiracamus/items/bc3bdfc206b39e0a75b2)

内部的な話なので優先度が低いとは思いますが検討頂けると幸いです。
方針示して頂ければこちらで変更してプルリクすることも可能です！

**Comment by tks3210** [comment]
issue化して頂きありがとうございます！
PEP8、ちゃんと認識したことがなかったのでちぐはぐになってました・・・！

下記の項目だけ、折を見て優先的に取り組みたいと思います～

関数、メソッド | 小文字のみ、必要に応じて単語をアンダースコアで区切る
非公開、プライベート | 先頭にアンダースコアを1個つける
定数 | 大文字のみ、単語をアンダースコアで区切る
変数 | 小文字のみ、必要に応じて単語をアンダースコアで区切る
